#!/usr/bin/env bash
# install and configure HAprozy in the server
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cat >> /etc/haproxy/haproxy.cfg << EOL
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 173177-web-01 54.242.189.76:80 check
    server 173177-web-02 18.204.11.235:80 check
EOL
sudo /etc/init.d/haproxy restart
