#!/usr/bin/env bash
# install and configure HAprozy in the server
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cat >> /etc/haproxy/haproxy.cfg << EOL
frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 1269-web-01 18.205.60.58:80 check
    server 1269-web-02 18.205.56.71:80 check
EOL
sudo /etc/init.d/haproxy restart
