#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59
x=0
while [ $x -le 12 ]
do
    echo "Hour: $x"
    i=1
    while [ $i -le 59 ]
    do
        echo $i
	i=$(( i + 1 ))
    done
    x=$(( x + 1 ))
done
