#!/usr/bin/env bash
# Change your home IP
cp -f /etc/hosts ~/hosts.new
sed -i 's/.*[0-9]*localhost/127.0.0.2\tlocalhost/' ~/hosts.new
sed -i '/.*[0-9]*facebook.com/d' ~/hosts.new
sed -i '$ a 8.8.8.8\tfacebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
