#!/usr/bin/env bash
#This is a Bash Script should run the whoami command 
# under the user passed as an argument
#!/bin/bash

if who -u | grep -q "^$user "; then
    top -u "$user"
else
    echo "$1"
fi
