#!/usr/bin/env bash
# This is a Bash script that fixes a container so that Nginx is running as the nginx user.

sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chmod 755 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start