#!/usr/bin/env bash
# This is a Bash script that fixes a container short

sudo su
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
